services:
  movies-db:
    image: postgres:17-alpine
    restart: always
    env_file:
      - ./.env
    volumes:
      - movie-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${MOVIE_DB_NAME}
      - POSTGRES_USER=${MOVIE_DB_USER}
      - POSTGRES_PASSWORD=${MOVIE_DB_PASSWORD}
    ports:
      - '${MOVIE_DB_PORT}:${MOVIE_DB_PORT}'
  reviews-db:
    image: mongo:8.2.4
    environment:
      - MONGO_INITDB_DATABASE=${REVIEW_DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${REVIEW_DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${REVIEW_DB_PASSWORD}
    ports:
      - '${REVIEW_DB_PORT}:${REVIEW_DB_PORT}'
    volumes:
      - review-data:/var/lib/mongodb/data

volumes:
  movie-data: {}
  review-data: {}